apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adapt.fullname" . }}
  labels:
    {{- include "adapt.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adapt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adapt.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.licenseServer.hostname }}
      hostname: {{ .Values.licenseServer.hostname }}
      {{- end }}
      serviceAccountName: {{ include "adapt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.deployProduct }}
      initContainers:
        - name: {{ include "adapt.fullname" . }}-deploy-ua
          image: "{{ .Values.ua.image.name }}:{{ .Values.ua.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ua.image.pullPolicy }}
          args: [share]
          volumeMounts:
            - name: ua-share
              mountPath: /opt/adapt/share
          {{- with .Values.ua.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ include "adapt.fullname" . }}-license-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.licenseServer.image.name }}:{{ .Values.licenseServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.licenseServer.image.pullPolicy }}
          ports:
            - name: daemon
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ls-config
              mountPath: /opt/adapt/ls/cdplicser.cfg
              subPath: cdplicser.cfg
          {{- if .Values.deployProduct }}
            - name: ua-share
              mountPath: /opt/adapt/ua
          {{- end }}
          {{- with .Values.licenseServer.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: ls-config
          configMap:
            name: {{ include "adapt.fullname" . }}-ls-config
      {{- if .Values.deployProduct }}
        - name: ua-share
          emptyDir: {}
      {{- with .Values.ua.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.licenseServer.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
