kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "adapt.fullname" . }}-ls-config
  labels:
    {{- include "adapt.labels" . | nindent 4 }}
data:
  cdplicser.cfg: |
    [SETTINGS]
    LISTEN_PORT=5000
    LICENSE_FILE={{ .Values.licenseServer.licenseFile }}
    LOG_FILE={{ .Values.licenseServer.logFile }}
