apiVersion: v1
kind: Service
metadata:
  name: {{ include "adapt.fullname" . }}
  labels:
    {{- include "adapt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: daemon
  selector:
    {{- include "adapt.selectorLabels" . | nindent 4 }}
