{{- if .Values.global.adapt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inspire.applicationName" . }}-adaptls
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
  annotations:
    description: Service for Adapt License Server
    {{- with .Values.service.annotations }}
    {{ tpl (toYaml .) $ | indent 4 }}
    {{- end }}
{{- with .Values.service.annotations }}
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
spec:
  ports:
    - name: {{ include "inspire.applicationName" . }}-adaptls-port
      port: {{ .Values.global.adapt.portOverride | default 5000 }}
      targetPort: 5000
  selector:
    app: {{ include "inspire.applicationName" . }}
    role: adaptls
  type: {{ .Values.service.type }}
  sessionAffinity: None
{{- end }}
