{{- if .Values.global.adapt.enabled }}
{{- if empty .Values.existingServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inspire.applicationName" . }}-adaptls
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
